### ISSUE TITLE
name mismatch issue

### ISSUE THREAD

**Issue by sakinaboriwala** [emz-hanauer/dart-cryptography#6]
I just want to override this dependency as one my dependencies uses this package internally. Added the following in pubspec.yaml file but getting an error.

```
dependency_overrides:
  cryptography_flutter: 
    git:
      url: https://github.com/emz-hanauer/dart-cryptography.git
      ref: master
      path: cryptography_flutter
  cryptography: 
    git:
      url: https://github.com/emz-hanauer/dart-cryptography.git
      ref: master
      path: cryptography
```

```
Error on line 1, column 7: "name" field doesn't match expected name "cryptography".
  ╷
1 │ name: cryptography_plus
```

how do I refer this repository?
